#!/bin/bash

set -e

# vars
logfile=$basedir/setup_log.md

export TZ=JST-9

#--------------------------------------
# minikube
minikube_status() {
  cmd="minikube status"
  exec_command "$cmd" || return $?
}
minikube_start() {
  cmd="minikube start --cpus='no-limit' --memory='no-limit' --insecure-registry='192.168.0.0/16'"
  exec_command "$cmd" || return $?
}
#--------------------------------------

#--------------------------------------
# kubectl
kubectl_check_ns() {
  cmd="kubectl get ns $1"
  exec_command "$cmd" || return $?
}
kubectl_add_ns() {
  cmd="kubectl create ns $1"
  exec_command "$cmd" || return $?
}
kubectl_wait_exists() {
  resource=$1
  name=$2
  namespace=$3
  if [ ! -z $namespace ]; then
    namespace=" -n $namespace"
  fi
  cmd="kubectl get $resource $name$namespace"
  exec_command "$cmd" || return $?
}
kubectl_wait() {
  args=$1
  namespace=$2
  timeout=${3:-120s}
  cmd="kubectl wait -n $namespace $args --timeout $timeout"
  exec_command "$cmd" || return $?
}
kubectl_check_portforward() {
  target=$1
  port=$2
  namespace=$3
  if [ ! -z $namespace ]; then
    namespace=" -n \"$namespace\""
  fi
  # close if pod not found
  curl -s localhost:${port/:*/} -o /dev/null || true
  cmd="ps -ef | grep \"port-forward $target$namespace $port\" | grep -v grep"
  exec_command "$cmd" || return $?
}
kubectl_portforward() {
  target=$1
  port=$2
  namespace=$3
  if [ ! -z $namespace ]; then
    namespace=" -n \"$namespace\""
  fi
  cmd="kubectl port-forward $target$namespace $port"
  exec_background_command "$cmd"
}

#--------------------------------------
# helm
## repo
helm_check_repo() {
  repo=$1
  cmd="helm repo list -o json | jq '[.[] | select (.name == \"$repo\")] | length'"
  exec_command "$cmd" "^1$" || return $?
}
helm_add_repo() {
  repo=$1
  url=$2
  cmd="helm repo add \"$repo\" \"$url\""
  exec_command "$cmd" || return $?
}
## install
helm_check_install() {
  name=$1
  namespace=$2
  if [ ! -z $namespace ]; then
    namespace=" -n \"$namespace\""
  fi
  cmd="helm list$namespace -o json | jq '[.[] | select (.name == \"$name\")] | length'"
  exec_command "$cmd" "^1$" || return $?
}
helm_install() {
  name=$1
  chart=$2
  namespace=$3
  args=$4
  if [ ! -z $namespace ]; then
    namespace=" -n \"$namespace\""
  fi
  if [ ! -z "$args" ]; then
    args=" $args"
  fi
  cmd="helm install$args $name $chart$namespace"
  exec_command "$cmd" || return $?
}
  
#--------------------------------------
# argocd
argocd_check_cli() {
  check_cli "argocd" || return $?
}
argocd_install_cli() {
  cmd="curl -sSL -o /tmp/argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64; sudo install -m 555 /tmp/argocd-linux-amd64 /usr/local/bin/argocd; rm /tmp/argocd-linux-amd64"
  exec_command "$cmd" || return $?
}
argocd_login() {
  port=$1
  password=$2
  cmd="yes | argocd login localhost:$port --username admin --password $password"
  exec_command "$cmd" || return $?
}
argocd_check_app() {
  cmd="argocd app list -o json | jq '[.[] | select (.metadata.name == \"$1\")] | length'"
  exec_command "$cmd" "^1$" || return $?
}
argocd_create_helm_app() {
  name=$1
  repo=$2
  chart=$3
  version=$4
  namespace=$5
  args=$6
  if [ ! -z $namespace ]; then
    namespace=" --dest-namespace $namespace"
  else
    namespace=" --dest-namespace default"
  fi
  if [ ! -z "$args" ]; then
    args=" $args"
  fi
  cmd="argocd app create $name --repo $repo --helm-chart $chart --dest-server https://kubernetes.default.svc$namespace --revision $version --sync-policy auto --sync-option CreateNamespace=true$args"
  exec_command "$cmd" || return $?
}
argocd_create_git_app() {
  name=$1
  repo=$2
  path=$3
  namespace=$4
  args=$5
  if [ ! -z $namespace ]; then
    namespace=" --dest-namespace $namespace"
  else
    namespace=" --dest-namespace default"
  fi
  if [ ! -z "$args" ]; then
    args=" $args"
  fi
  cmd="argocd app create $name --repo $repo --path $path --dest-server https://kubernetes.default.svc$namespace --sync-policy auto$args"
  exec_command "$cmd" || return $?
}

#--------------------------------------
# gitea
gitea_check_repo() {
  endpoint=$1
  user=$2
  pass=$3
  repo=$4
  cmd="curl -s -X GET -u \"$user:$pass\" http://$endpoint/api/v1/user/repos | jq '[ .[] | select (.name == \"$repo\")] | length'"
  exec_command "$cmd" "^1$" || return $?
}
gitea_create_repo() {
  endpoint=$1
  user=$2
  pass=$3
  repo=$4
  cmd="curl -v -s -X POST -H 'Content-Type: application/json' -u \"$user:$pass\" -d '{ \"name\": \"$repo\" }' http://$endpoint/api/v1/user/repos"
  exec_command "$cmd" || return $?
}
gitea_check_repo_actions() {
  endpoint=$1
  user=$2
  pass=$3
  repo=$4
  cmd="curl -s -X GET -u \"$user:$pass\" http://$endpoint/api/v1/repos/$user/$repo | jq '.has_actions'"
  exec_command "$cmd" "^true$" || return $?
}
gitea_enable_repo_actions() {
  endpoint=$1
  user=$2
  pass=$3
  repo=$4
  cmd="curl -v -s -X PATCH -H 'Content-Type: application/json' -u \"$user:$pass\" -d '{ \"has_actions\": true }' http://$endpoint/api/v1/repos/$user/$repo"
  exec_command "$cmd" || return $?
}
gitea_set_secret() {
  endpoint=$1
  user=$2
  pass=$3
  key=$4
  value=$5
  cmd="curl -s -X PUT -H 'Content-Type: application/json' -u \"$user:$pass\" -d '{ \"data\": \"$value\" }' http://$endpoint/api/v1/user/actions/secrets/$key -w '%{http_code}'"
  exec_command "$cmd" "^20.$" || return $?
}
gitea_check_access_token() {
  endpoint=$1
  user=$2
  pass=$3
  name=$4
  cmd="curl -s -X GET -u \"$user:$pass\" http://$endpoint/api/v1/users/$user/tokens | jq '[ .[] | select (.name == \"$name\")] | length'"
  exec_command "$cmd" "^1$" || return $?
}
gitea_create_access_token() {
  endpoint=$1
  user=$2
  pass=$3
  name=$4
  scopes=$5
  cmd="curl -s -X POST -H 'Content-Type: application/json' -u \"$user:$pass\" -d '{ \"name\": \"$name\", \"scopes\": $scopes }' http://$endpoint/api/v1/users/$user/tokens | jq -r .sha1"
  exec_command_out "$cmd"
}
gitea_check_cli() {
  check_cli "tea" || return $?
}
gitea_install_cli() {
  cmd="curl -sSL -o /tmp/tea-0.9.2-linux-amd64 https://gitea.com/gitea/tea/releases/download/v0.9.2/tea-0.9.2-linux-amd64; sudo install -m 555 /tmp/tea-0.9.2-linux-amd64 /usr/local/bin/tea; rm /tmp/tea-0.9.2-linux-amd64"
  exec_command "$cmd" || return $?
}

#--------------------------------------
# harbor
harbor_login() {
  url=$1
  user=$2
  pass=$3
  cmd="docker login $url -u $user -p $pass"
  exec_command "$cmd" || return $?
}

#--------------------------------------
# hosts
hosts_check() {
  host=$1
  ip=$2
  cmd="grep $host /etc/hosts | grep $ip"
  exec_command "$cmd" || return $?
}
hosts_update() {
  host=$1
  ip=$2
  cmd="echo $ip $host | sudo tee -a /etc/hosts"
  exec_command "$cmd" || return $?
}
hosts_check_minikube() {
  host=$1
  ip=$2
  cmd="minikube ssh grep $host /etc/hosts | grep $ip"
  exec_command "$cmd" || return $?
}
hosts_update_minikube() {
  host=$1
  ip=$2
  cmd="minikube ssh \"echo $ip $host | sudo tee -a /etc/hosts\""
  exec_command "$cmd" || return $?
}

#--------------------------------------
# socat
socat_check_cli() {
  check_cli "socat" || return $?
}
socat_install_cli() {
  exec_command "sudo apt install -y socat" || return $?
}
socat_check_portforward() {
  listen=$1
  ip=$2
  port=$3
  cmd="ps -ef | grep \"socat TCP-LISTEN:$listen,fork,reuseaddr TCP4:$ip:$port\" | grep -v grep"
  exec_command "$cmd" || return $?
}
socat_portforward() {
  listen=$1
  ip=$2
  port=$3
  cmd="socat TCP-LISTEN:$listen,fork,reuseaddr TCP4:$ip:$port"
  exec_background_command "$cmd"
}

#--------------------------------------
# misc
google_cloudshell() {
  test -d /google || return $?
}
check_cli() {
  cmd="which $1"
  exec_command "$cmd" || return $?
}
check_listening() {
  port=$1
  cmd="ss -o state listening sport = $port -np | grep $port"
  exec_command "$cmd" || return $?
}
java_set_17() {
  # for cloudshell ephemeral
  if [ "$JAVA_HOME" == "/usr/lib/jvm/java-11-openjdk-amd64" ]; then
    if [ -d "/usr/lib/jvm/java-17-openjdk-amd64" ]; then
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    else
      return 1
    fi
  fi
}

#--------------------------------------
# command
exec_command() {
  status=0
  expect_regex=$2
  command_log_start "$1"
  if [ -z $expect_regex ]; then
    eval " $1" >>$logfile 2>&1 || status=$?
  else
    output=$(eval " $1" 2>&1)
    echo $output >>$logfile
    [[ "$output" =~ $expect_regex ]] || status=$?
  fi
  command_log_end "$1"
  return $status
}
exec_background_command() {
  out=${2:-/dev/null}
  command_log_start "$1"
  eval " $1" >>$out 2>&1 &
  command_log_end "$1"
}
exec_command_out() {
  command_log_start "$1"
  output=$(eval " $1" 2>&1)
  echo $output | tee -a $logfile
  command_log_end "$1"
}

#--------------------------------------
# logging
command_log_start() {
  echo "- \`$(now)\` - COMMAND" >>$logfile
  echo '```bash' >>$logfile
  echo "$1" >>$logfile
  echo '```' >>$logfile
  echo '```terminal' >>$logfile
}
command_log_end() {
  echo '```' >>$logfile
  echo >>$logfile
}
#--------------------------------------

ok() {
  echo "ok"
}
ng() {
  echo "ng"
}
fail() {
  echo "fail"
  exit 1
}
now() {
  date "+%Y-%m-%d %H:%M:%S"
}
retry() {
  max_tries="$1"; shift
  command="$@"
  attempt_num=1

  until $command
  do
    if ((attempt_num==max_tries)); then
      return 1
    else
      sleep $attempt_num
      ((attempt_num++))
    fi
  done
}
